version: '3'
# docker-compose.yml
networks:
  proxy:
    external:
      name: common_proxy
services:
  release_mysql:
    container_name: release_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "dev*I(O)P"
      #MYSQL_DATABASE: sphokidz
      #MYSQL_USER: sphokidz
      #MYSQL_PASSWORD: "dev*I(O)P"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - 3320:3306
    networks:
      - proxy
